"""
Generate type-safe wrapper functions for Facebook Business SDK API methods.

Supports manual sections in generated files:
- ---- BEGIN MANUAL SECTION ----
- ---- END MANUAL SECTION ----
Anything between these markers will be preserved during regeneration.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from generate_models import AdObjectInfo, ApiMethodInfo, FacebookSDKParser, extract_manual_sections


@dataclass
class WrapperFunctionInfo:
    """Information needed to generate a wrapper function."""

    object_name: str  # e.g., "Campaign"
    method_name: str  # e.g., "get_ads"
    http_method: str  # GET, POST, DELETE
    endpoint: str  # e.g., "/ads"
    target_class: Optional[str]  # e.g., "Ad"
    param_model: Optional[str]  # e.g., "CampaignGetAdsParams"
    field_literal: Optional[str]  # e.g., "AdField"
    returns_iterator: bool = True


class WrapperGenerator:
    """Generate type-safe wrapper functions for AdObject methods."""

    def __init__(self):
        self.parser = FacebookSDKParser()

    def generate_wrappers_file(
        self, adobject_info: AdObjectInfo, output_dir: Path
    ) -> Optional[str]:
        """Generate a file with wrapper functions for an AdObject."""
        if not adobject_info.api_methods:
            return None

        # Output file path
        output_file = output_dir / f"{adobject_info.module_path}_wrappers.py"

        # Extract manual sections from existing file if it exists
        manual_sections = extract_manual_sections(output_file) if output_file.exists() else {}

        lines = []
        lines.append('"""Code generated by PromoBase script - DO NOT EDIT MANUALLY."""')
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("")
        lines.append("from typing import Any")
        lines.append("")
        lines.append(
            f"from facebook_business.adobjects.{adobject_info.module_path} import {adobject_info.name}"
        )
        lines.append("")

        # Import the models
        lines.append(f"from ..models.{adobject_info.module_path} import (")
        lines.append(f"    {adobject_info.name}Field,")

        # Import param models
        param_models = set()
        for method_info in adobject_info.api_methods:
            param_model_name = self._get_param_model_name(adobject_info.name, method_info.name)
            param_models.add(param_model_name)

        for param_model in sorted(param_models):
            lines.append(f"    {param_model},")
        lines.append(")")
        lines.append("")

        # Always add manual imports section
        manual_imports_content = manual_sections.get("imports", "")
        lines.append("# ---- BEGIN MANUAL SECTION: imports ----")
        lines.append(manual_imports_content)
        lines.append("# ---- END MANUAL SECTION: imports ----")
        lines.append("")

        # Import target class models if needed
        target_imports = {}
        for method_info in adobject_info.api_methods:
            if method_info.target_class and method_info.target_class != adobject_info.name:
                # Skip abstract base classes
                if method_info.target_class == "AbstractCrudObject":
                    continue
                target_module = self._get_module_name(method_info.target_class)
                if target_module:
                    if target_module not in target_imports:
                        target_imports[target_module] = set()
                    target_imports[target_module].add(f"{method_info.target_class}Field")

        for module, classes in sorted(target_imports.items()):
            lines.append(f"from ..models.{module} import {', '.join(sorted(classes))}")

        if target_imports:
            lines.append("")

        # Always add manual pre-functions section (for model_rebuild calls)
        # Check for both old and new section names for backwards compatibility
        manual_pre_functions_content = manual_sections.get(
            "pre_functions", ""
        ) or manual_sections.get("pre_class", "")
        lines.append("# ---- BEGIN MANUAL SECTION: pre_functions ----")
        lines.append(manual_pre_functions_content)
        lines.append("# ---- END MANUAL SECTION: pre_functions ----")
        lines.append("")

        # Generate wrapper functions
        for method_info in adobject_info.api_methods:
            wrapper_lines = self._generate_wrapper_function(adobject_info, method_info)
            lines.extend(wrapper_lines)
            lines.append("")
            lines.append("")

        # Always add manual end section
        manual_end_content = manual_sections.get("end", "")
        lines.append("# ---- BEGIN MANUAL SECTION: end ----")
        lines.append(manual_end_content)
        lines.append("# ---- END MANUAL SECTION: end ----")

        # Write the file
        with open(output_file, "w") as f:
            f.write("\n".join(lines))

        return output_file

    def _get_param_model_name(self, class_name: str, method_name: str) -> str:
        """Get the parameter model name for a method."""
        # Convert method name to PascalCase
        parts = method_name.split("_")
        pascal_name = "".join(word.capitalize() for word in parts)
        return f"{class_name}{pascal_name}Params"

    def _get_module_name(self, class_name: str) -> Optional[str]:
        """Get the module name for a class."""
        # Convert PascalCase to snake_case

        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", class_name)
        module_name = re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()

        # Check if this module exists in our adobject types
        if class_name in self.parser._adobject_types:
            return self.parser._adobject_types[class_name]
        return module_name

    def _generate_wrapper_function(
        self, adobject_info: AdObjectInfo, method_info: ApiMethodInfo
    ) -> list[str]:
        """Generate a standalone function that uses generated params but raw API calls."""
        lines = []

        param_model_name = self._get_param_model_name(adobject_info.name, method_info.name)

        # Determine return type - keep it simple with Any for now
        return_type = "Any"

        # Generate function signature
        if method_info.name.startswith("get_"):
            lines.append(f"def {method_info.name}(")
            lines.append(f"    {adobject_info.module_path}_id: str,")
            if method_info.target_class and method_info.target_class != "AbstractCrudObject":
                target_field = f"{method_info.target_class}Field"
                lines.append(f"    fields: list[{target_field}] = [],")
            else:
                lines.append("    fields: list[str] = [],")
            lines.append(f"    params: {param_model_name} = {{}},")
            lines.append(f") -> {return_type}:")

        elif method_info.name.startswith("create_"):
            lines.append(f"def {method_info.name}(")
            lines.append(f"    {adobject_info.module_path}_id: str,")
            lines.append("    fields: list[str] = [],")
            lines.append(f"    params: {param_model_name} = {{}},")
            lines.append(f") -> {return_type}:")

        else:  # delete_ or other methods
            lines.append(f"def {method_info.name}(")
            lines.append(f"    {adobject_info.module_path}_id: str,")
            if method_info.param_types:
                lines.append(f"    params: {param_model_name} = {{}},")
            lines.append(f") -> {return_type}:")

        # Generate docstring
        lines.append(
            f'    """{method_info.name.replace("_", " ").title()} for this {adobject_info.name}.'
        )
        lines.append("")
        lines.append("    Args:")
        lines.append(f"        {adobject_info.module_path}_id: The ID of the {adobject_info.name}.")
        if method_info.name.startswith("get_") or method_info.name.startswith("create_"):
            lines.append("        fields: Fields to retrieve.")
        if method_info.name.startswith("get_") or method_info.name.startswith("create_"):
            lines.append("        params: Query parameters.")
        elif method_info.param_types:
            lines.append("        params: Parameters for the operation.")
        lines.append('    """')

        # Generate method body - direct API call
        lines.append(
            f"    return {adobject_info.name}({adobject_info.module_path}_id).{method_info.name}("
        )
        if method_info.name.startswith("get_") or method_info.name.startswith("create_"):
            lines.append("        fields=fields,")
            lines.append("        params=params")
        elif method_info.param_types:
            lines.append("        params=params")
        lines.append("    )")

        return lines


def main():
    """Generate wrapper functions for all AdObjects."""
    parser = FacebookSDKParser()
    generator = WrapperGenerator()

    # Output directory
    output_dir = Path("src/generated/wrappers")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Note: We no longer delete existing wrapper files to preserve manual sections
    print("Checking for old wrapper files...")
    # Only clean up if this is the first run (no existing files)
    existing_wrappers = list(output_dir.glob("*_wrappers.py"))
    if not existing_wrappers:
        print("  No existing wrapper files found, starting fresh")

    # Process all AdObject files
    adobject_files = parser.find_adobject_files()

    # Filter out non-adobject files (like __init__.py, abstractobject.py, etc.)
    files_to_process = []
    for file_path in adobject_files:
        # Skip special files
        if file_path.stem.startswith("__") or file_path.stem in [
            "abstractobject",
            "abstractcrudobject",
            "apispecfile",
        ]:
            continue
        files_to_process.append(file_path)

    print(f"\nFound {len(files_to_process)} ad object files to process")

    generated_wrappers = []
    wrapper_count = 0

    for file_path in files_to_process:
        adobject_info = parser.parse_file(file_path)

        if adobject_info and adobject_info.api_methods:
            output_file = generator.generate_wrappers_file(adobject_info, output_dir)
            if output_file:
                generated_wrappers.append(output_file)
                wrapper_count += len(adobject_info.api_methods)
                print(f"  ✓ Generated {output_file.name}")
                print(f"    - {len(adobject_info.api_methods)} API methods wrapped")

    # Generate __init__.py
    init_file = output_dir / "__init__.py"
    with open(init_file, "w") as f:
        f.write('"""Code generated by PromoBase script - DO NOT EDIT MANUALLY."""\n')
        f.write('"""Type-safe wrappers for Facebook Business SDK API methods."""\n')
        f.write('"""\n')
        f.write("Note: Due to naming conflicts, functions are not re-exported here.\n")
        f.write("Import directly from the specific wrapper modules instead:\n")
        f.write("\n")
        f.write("from src.generated.wrappers.adaccount_wrappers import get_campaigns\n")
        f.write("from src.generated.wrappers.campaign_wrappers import get_ad_sets\n")
        f.write('"""\n\n')

        # List all available modules for reference
        f.write("# Available wrapper modules:\n")
        for wrapper_file in sorted(generated_wrappers):
            module_name = wrapper_file.stem
            f.write(f"# - {module_name}\n")

        f.write("\n")
        f.write("__all__ = []  # Due to naming conflicts, import from specific modules\n")

    print(
        f"\n✓ Generated {len(generated_wrappers)} wrapper files with {wrapper_count} total methods"
    )
    print("✓ Generated __init__.py")

    # Ruff formatting will be done by the main codegen.py script


if __name__ == "__main__":
    main()
