"""
Generate type-safe wrapper functions for Facebook Business SDK API methods.

Supports manual sections in generated files:
- ---- BEGIN MANUAL SECTION ----
- ---- END MANUAL SECTION ----
Anything between these markers will be preserved during regeneration.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from generate_models import AdObjectInfo, ApiMethodInfo, FacebookSDKParser, extract_manual_sections


@dataclass
class WrapperFunctionInfo:
    """Information needed to generate a wrapper function."""

    object_name: str  # e.g., "Campaign"
    method_name: str  # e.g., "get_ads"
    http_method: str  # GET, POST, DELETE
    endpoint: str  # e.g., "/ads"
    target_class: Optional[str]  # e.g., "Ad"
    param_model: Optional[str]  # e.g., "CampaignGetAdsParams"
    field_literal: Optional[str]  # e.g., "AdField"
    returns_iterator: bool = True


class WrapperGenerator:
    """Generate type-safe wrapper functions for AdObject methods."""

    def __init__(self):
        self.parser = FacebookSDKParser()

    def generate_wrappers_file(
        self, adobject_info: AdObjectInfo, output_dir: Path
    ) -> Optional[str]:
        """Generate a file with wrapper functions for an AdObject."""
        if not adobject_info.api_methods:
            return None

        # Output file path
        output_file = output_dir / f"{adobject_info.module_path}_wrappers.py"

        # Extract manual sections from existing file if it exists
        manual_sections = extract_manual_sections(output_file) if output_file.exists() else {}

        lines = []
        lines.append('"""Code generated by PromoBase script - DO NOT EDIT MANUALLY."""')
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("")
        lines.append("from typing import Any, Optional, TYPE_CHECKING")
        lines.append("")
        lines.append("if TYPE_CHECKING:")
        lines.append(
            f"    from facebook_business.adobjects.{adobject_info.module_path} import {adobject_info.name}"
        )
        lines.append("")
        lines.append("from .cursor_utils import TypedCursor")
        lines.append("")

        # Import the models
        lines.append(f"from ..models.{adobject_info.module_path} import (")
        lines.append(f"    {adobject_info.name}Fields,")
        lines.append(f"    {adobject_info.name}Field,")

        # Import param models
        param_models = set()
        for method_info in adobject_info.api_methods:
            param_model_name = self._get_param_model_name(adobject_info.name, method_info.name)
            param_models.add(param_model_name)

        for param_model in sorted(param_models):
            lines.append(f"    {param_model},")
        lines.append(")")
        lines.append("")

        # Always add manual imports section
        manual_imports_content = manual_sections.get("imports", "")
        lines.append("# ---- BEGIN MANUAL SECTION: imports ----")
        lines.append(manual_imports_content)
        lines.append("# ---- END MANUAL SECTION: imports ----")
        lines.append("")

        # Import target class models if needed
        target_imports = {}
        for method_info in adobject_info.api_methods:
            if method_info.target_class and method_info.target_class != adobject_info.name:
                # Skip abstract base classes
                if method_info.target_class == "AbstractCrudObject":
                    continue
                target_module = self._get_module_name(method_info.target_class)
                if target_module:
                    if target_module not in target_imports:
                        target_imports[target_module] = set()
                    target_imports[target_module].add(f"{method_info.target_class}Fields")
                    target_imports[target_module].add(f"{method_info.target_class}Field")

        for module, classes in sorted(target_imports.items()):
            lines.append(f"from ..models.{module} import (")
            for cls in sorted(classes):
                lines.append(f"    {cls},")
            lines.append(")")
        lines.append("")

        # Always add manual pre-class section (for model_rebuild calls)
        manual_pre_class_content = manual_sections.get("pre_class", "")
        lines.append("# ---- BEGIN MANUAL SECTION: pre_class ----")
        lines.append(manual_pre_class_content)
        lines.append("# ---- END MANUAL SECTION: pre_class ----")
        lines.append("")

        # Generate wrapper class
        lines.append(f"class {adobject_info.name}Wrappers:")
        lines.append(f'    """Type-safe wrapper functions for {adobject_info.name} API methods."""')
        lines.append("")

        # Generate wrapper methods
        for method_info in adobject_info.api_methods:
            wrapper_lines = self._generate_wrapper_method(adobject_info, method_info)
            lines.extend(wrapper_lines)
            lines.append("")

        # Always add manual end section
        manual_end_content = manual_sections.get("end", "")
        lines.append("")
        lines.append("# ---- BEGIN MANUAL SECTION: end ----")
        lines.append(manual_end_content)
        lines.append("# ---- END MANUAL SECTION: end ----")

        # Write the file
        with open(output_file, "w") as f:
            f.write("\n".join(lines))

        return output_file

    def _get_param_model_name(self, class_name: str, method_name: str) -> str:
        """Get the parameter model name for a method."""
        # Convert method name to PascalCase
        parts = method_name.split("_")
        pascal_name = "".join(word.capitalize() for word in parts)
        return f"{class_name}{pascal_name}Params"

    def _get_module_name(self, class_name: str) -> Optional[str]:
        """Get the module name for a class."""
        # Convert PascalCase to snake_case

        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", class_name)
        module_name = re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()

        # Check if this module exists in our adobject types
        if class_name in self.parser._adobject_types:
            return self.parser._adobject_types[class_name]
        return module_name

    def _generate_wrapper_method(
        self, adobject_info: AdObjectInfo, method_info: ApiMethodInfo
    ) -> list[str]:
        """Generate a wrapper method for an API method."""
        lines = []

        # Method signature
        lines.append("    @staticmethod")

        param_model_name = self._get_param_model_name(adobject_info.name, method_info.name)

        # Determine return type
        if method_info.target_class:
            # Skip abstract base classes - return dict instead
            if method_info.target_class == "AbstractCrudObject":
                if method_info.http_method == "GET" and method_info.name != "api_get":
                    return_type = "list[dict[str, Any]]"  # Cursor returns list
                else:
                    return_type = "dict[str, Any]"
            else:
                # Special case: get_insights_async is a POST method but still named get_*
                if method_info.http_method == "GET" and method_info.name != "api_get":
                    # GET methods on EDGE endpoints return Cursor objects for pagination
                    return_type = f"TypedCursor[{method_info.target_class}Fields]"
                else:
                    return_type = f"{method_info.target_class}Fields"
        else:
            return_type = "dict[str, Any]"

        # Generate method signature
        if method_info.name.startswith("get_"):
            lines.append(f"    def {method_info.name}(")
            lines.append(f"        obj: {adobject_info.name},")
            lines.append(f"        params: Optional[{param_model_name}] = None,")
            if method_info.target_class and method_info.target_class != "AbstractCrudObject":
                target_field = f"{method_info.target_class}Field"
                lines.append(f"        fields: Optional[list[{target_field}]] = None,")
            else:
                lines.append("        fields: Optional[list[str]] = None,")
            lines.append(f"    ) -> {return_type}:")

        elif method_info.name.startswith("create_"):
            lines.append(f"    def {method_info.name}(")
            lines.append(f"        obj: {adobject_info.name},")
            lines.append(f"        params: {param_model_name},")
            lines.append(f"    ) -> {return_type}:")

        else:  # delete_
            lines.append(f"    def {method_info.name}(")
            lines.append(f"        obj: {adobject_info.name},")
            if method_info.param_types:
                lines.append(f"        params: Optional[{param_model_name}] = None,")
            lines.append("    ) -> bool:")

        # Generate docstring
        lines.append('        """')
        lines.append(f"        Type-safe wrapper for {adobject_info.name}.{method_info.name}().")
        if method_info.endpoint:
            lines.append("        ")
            lines.append(f"        Endpoint: {method_info.http_method} {method_info.endpoint}")
        if method_info.target_class:
            lines.append(f"        Returns: {return_type}")
        lines.append('        """')

        # Generate method body
        lines.append("        # Convert params to dict if provided")
        lines.append(
            "        params_dict = params.model_dump(exclude_none=True, by_alias=True) if params else None"
        )

        if method_info.name.startswith("get_") and method_info.target_class:
            lines.append("        ")
            lines.append("        # Convert fields to list of strings")
            lines.append("        fields_list = list(fields) if fields else None")
            lines.append("        ")
            lines.append("        # Call the original method")
            if method_info.http_method == "GET":
                lines.append(f"        cursor = obj.{method_info.name}(")
                lines.append("            params=params_dict,")
                lines.append("            fields=fields_list,")
                lines.append("        )")
                lines.append("        ")
                if method_info.target_class == "AbstractCrudObject":
                    lines.append("        # Return raw cursor data for abstract base class")
                    lines.append("        return [item.export_all_data() for item in cursor]")
                else:
                    lines.append("        # Wrap the cursor for type safety")
                    lines.append(
                        f"        return TypedCursor(cursor, {method_info.target_class}Fields)"
                    )
            else:
                # This is a POST method that happens to start with get_ (like get_insights_async)
                lines.append(f"        result = obj.{method_info.name}(")
                lines.append("            params=params_dict,")
                lines.append("            fields=fields_list,")
                lines.append("        )")
                lines.append("        ")
                if method_info.target_class == "AbstractCrudObject":
                    lines.append("        # Return raw data for abstract base class")
                    lines.append(
                        "        return result.export_all_data() if hasattr(result, 'export_all_data') else result"
                    )
                else:
                    lines.append("        # Convert result to typed model")
                    lines.append(f"        return {method_info.target_class}Fields(**result)")

        elif method_info.name.startswith("create_"):
            lines.append("        ")
            lines.append("        # Call the original method")
            lines.append(f"        result = obj.{method_info.name}(params=params_dict)")
            lines.append("        ")
            if method_info.target_class == "AbstractCrudObject":
                lines.append("        # Return raw data for abstract base class")
                lines.append(
                    "        return result.export_all_data() if hasattr(result, 'export_all_data') else result"
                )
            else:
                lines.append("        # Convert result to typed model")
                lines.append(
                    f"        return {method_info.target_class or adobject_info.name}Fields(**result)"
                )

        else:  # delete_
            lines.append("        ")
            lines.append("        # Call the original method")
            if method_info.param_types:
                lines.append(f"        obj.{method_info.name}(params=params_dict)")
            else:
                lines.append(f"        obj.{method_info.name}()")
            lines.append("        ")
            lines.append("        return True  # Delete methods typically don't return anything")

        return lines


def main():
    """Generate wrapper functions for all AdObjects."""
    parser = FacebookSDKParser()
    generator = WrapperGenerator()

    # Output directory
    output_dir = Path("src/generated/wrappers")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Clean up existing files
    print("Cleaning up existing wrapper files...")
    for old_file in output_dir.glob("*.py"):
        # Don't delete __init__.py or cursor_utils.py
        if not old_file.stem.startswith("__") and old_file.stem != "cursor_utils":
            old_file.unlink()
            print(f"  Removed {old_file}")

    # Process all AdObject files
    adobject_files = parser.find_adobject_files()

    # Filter out non-adobject files (like __init__.py, abstractobject.py, etc.)
    files_to_process = []
    for file_path in adobject_files:
        # Skip special files
        if file_path.stem.startswith("__") or file_path.stem in [
            "abstractobject",
            "abstractcrudobject",
            "apispecfile",
        ]:
            continue
        files_to_process.append(file_path)

    print(f"\nFound {len(files_to_process)} ad object files to process")

    generated_wrappers = []
    wrapper_count = 0

    for file_path in files_to_process:
        adobject_info = parser.parse_file(file_path)

        if adobject_info and adobject_info.api_methods:
            output_file = generator.generate_wrappers_file(adobject_info, output_dir)
            if output_file:
                generated_wrappers.append(output_file)
                wrapper_count += len(adobject_info.api_methods)
                print(f"  ✓ Generated {output_file.name}")
                print(f"    - {len(adobject_info.api_methods)} API methods wrapped")

    # Generate __init__.py
    init_file = output_dir / "__init__.py"
    with open(init_file, "w") as f:
        f.write('"""Code generated by PromoBase script - DO NOT EDIT MANUALLY."""\n')
        f.write('"""Type-safe wrappers for Facebook Business SDK API methods."""\n\n')

        # Import all wrapper classes
        for wrapper_file in sorted(generated_wrappers):
            module_name = wrapper_file.stem
            # Get the actual class name from the adobject info
            # Find the matching adobject_info
            for file_path in files_to_process:
                adobject_info = parser.parse_file(file_path)
                if adobject_info and adobject_info.module_path + "_wrappers" == module_name:
                    class_name = f"{adobject_info.name}Wrappers"
                    f.write(f"from .{module_name} import {class_name}\n")
                    break

        f.write("\n__all__ = [\n")
        for wrapper_file in sorted(generated_wrappers):
            module_name = wrapper_file.stem
            # Get the actual class name from the adobject info
            for file_path in files_to_process:
                adobject_info = parser.parse_file(file_path)
                if adobject_info and adobject_info.module_path + "_wrappers" == module_name:
                    class_name = f"{adobject_info.name}Wrappers"
                    f.write(f'    "{class_name}",\n')
                    break
        f.write("]\n")

    print(
        f"\n✓ Generated {len(generated_wrappers)} wrapper files with {wrapper_count} total methods"
    )
    print("✓ Generated __init__.py")

    # Ruff formatting will be done by the main codegen.py script


if __name__ == "__main__":
    main()
